### ISSUE TITLE
Fastlane execution sticks at Waiting for available resources..

### ISSUE THREAD

**Issue by shasaaf** [xing/mango#36]
please let us know if need to provide any other parameter also

I have chosen a sample espresso repo and setup fastlane for it.

it gives Waiting for available resources.. message continuously without failing

**Comment by JoeSSS** [comment]
Hello, according to this line: https://github.com/xing/mango/blob/998d3a69e5a901b5e9b012e28eb6579e9a837da1/lib/fastlane/plugin/mango/helper/cpu_load_handler.rb#L27
the plugin will wait until the load is not higher that 1.5 amount of the CPUs on the machine where it runs. So if your machine has 4 cores and the load from (top or htop) shows current load that is more than 6, the plugin won't start working.

Another possibility is that maybe your linux distribution returns wrong amount of cores to this command: ```cat /proc/cpuinfo | awk '/^processor/{print $3}' | tail -1``` this will cause plugin to wait a lot.

**Comment by JoeSSS** [comment]
@shasaaf please check if your case is just a big load or the wrong cpu calculation

**Comment by shasaaf** [comment]
Thanks for the quick response.

After increasing the cores it started working after that step, now it says container status: unhealthy.

Do I need to include anything in the container itself?

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
[Capture]

**Comment by JoeSSS** [comment]
you need a container with the HEALTHCHECK block like: https://github.com/budtmo/docker-android/blob/master/docker/Emulator_x86#L200

**Comment by JoeSSS** [comment]
since there is no other way to check that emulator is actually started - we needed to force HEALTCHECK to be there

**Comment by shasaaf** [comment]
So should I manually change healthcheck part from a dockerfile and build a new image?

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
[Capture]

**Comment by JoeSSS** [comment]
If you use another dockerfile than the one we propose in usage section in Readme or the one I posted above and you do not have the HEALTCHCHECK block - then yes, you need to add it and rebuild

**Comment by shasaaf** [comment]
This image “joesss/mango-docker” from docker hub had a docker file with healthcheck like “HEALTHCHECK --timeout=10s”

The docker images with your name “budtmo<https://github.com/budtmo>/docker-android<https://github.com/budtmo/docker-android>” does it have similar conf for emulation and espresso?

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
[Capture]

**Comment by JoeSSS** [comment]
both images are good to go

**Comment by shasaaf** [comment]
Thanks for the help, but the container never comes in the healthy state, I have tried external arguments as well as built a new image with the new healthcheck, still it doesn’t come up.

Please help with any other image which can run the espresso and appium tests.
Please also clarify, for UI testing the emulator should be visible on the screen or it runs in the background and still works or runs the tests.

I am running the docker image as it is, without any modification, do I need to make any modification as well for my repo?

Please answer the above questions!

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
[Capture]

**Comment by JoeSSS** [comment]
You need to understand why containers do not start for you, it has nothing to do with the plugin. You can try running the container manually and check logs for errors (either docker logs or /var/log/supervisor/*)

**Comment by shasaaf** [comment]
Thanks
I did that, it runs manually for your image of 8.1

But doesnt run on fastlane
Says unhealthy

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
Publicis Sapient
________________________________

**Comment by JoeSSS** [comment]
Then maybe it takes too long to start the container? Try increase RAM and CPU. It would need around 8 cores and 8+ GB of ram to start quick. Also please share the console output when it fails to start

**Comment by shasaaf** [comment]
Sure I will ,
At this time the resource was 4 cores 8gb ram

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
Publicis Sapient
________________________________

**Comment by JoeSSS** [comment]
it may take too long to start with 4 cores then, please try to increase. Emulator eats quite some CPU

**Comment by shasaaf** [comment]
Sure, but it worked when I ran manually with docker run command and installed the apk pack and showed on emulator in the browser

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
Publicis Sapient
________________________________

**Comment by shasaaf** [comment]
This is the logs from docker logs

2020-06-29 02:00:20,856 INFO spawned: 'atd' with pid 48
2020-06-29 02:00:20,858 INFO spawned: 'auto-recording' with pid 49
2020-06-29 02:00:20,860 INFO spawned: 'adb-utils' with pid 51
2020-06-29 02:00:20,861 INFO exited: screen-copy (exit status 0; not expected)
2020-06-29 02:00:20,870 INFO exited: atd (exit status 0; not expected)
2020-06-29 02:00:21,894 INFO success: xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-29 02:00:21,894 INFO success: port-forward entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-29 02:00:21,895 INFO success: novnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-29 02:00:21,895 INFO success: openbox entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-29 02:00:21,895 INFO success: x11vnc entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-29 02:00:21,896 INFO spawned: 'screen-copy' with pid 169
2020-06-29 02:00:21,897 INFO success: docker-appium entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-29 02:00:21,899 INFO spawned: 'atd' with pid 170
2020-06-29 02:00:21,900 INFO success: auto-recording entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-29 02:00:21,900 INFO success: adb-utils entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-06-29 02:00:21,909 INFO exited: atd (exit status 0; not expected)
2020-06-29 02:00:21,919 INFO exited: screen-copy (exit status 0; not expected)
2020-06-29 02:00:22,340 INFO exited: docker-appium (exit status 1; not expected)
2020-06-29 02:00:24,344 INFO spawned: 'screen-copy' with pid 179
2020-06-29 02:00:24,345 INFO spawned: 'atd' with pid 180
2020-06-29 02:00:24,348 INFO exited: screen-copy (exit status 0; not expected)
2020-06-29 02:00:24,350 INFO exited: atd (exit status 0; not expected)
2020-06-29 02:00:26,875 INFO exited: auto-recording (exit status 0; expected)
2020-06-29 02:00:27,877 INFO spawned: 'screen-copy' with pid 181
2020-06-29 02:00:27,879 INFO spawned: 'atd' with pid 182
2020-06-29 02:00:27,883 INFO exited: screen-copy (exit status 0; not expected)
2020-06-29 02:00:27,884 INFO gave up: screen-copy entered FATAL state, too many start retries too quickly
2020-06-29 02:00:27,884 INFO exited: atd (exit status 0; not expected)
2020-06-29 02:00:28,886 INFO gave up: atd entered FATAL state, too many start retries too quickly


And from fastlane:

[09:00:22]: Container status: starting
[09:00:29]: Container status: starting
[09:00:36]: Container status: starting
[09:00:43]: Container status: starting
[09:00:50]: Container status: starting
[09:00:57]: Container status: starting
[09:01:04]: Container status: unhealthy
[09:01:11]: Container status: unhealthy
[09:01:18]: Container status: unhealthy
[09:01:25]: Container status: unhealthy
[09:01:32]: Container status: unhealthy
[09:01:39]: Container status: unhealthy
[09:01:44]: The Container failed to load after '60' seconds timeout. Reason: 'running'
[09:01:44]: Will retry to create a healthy docker container after 5 seconds
[09:01:59]: Creating container: espresso_container
[09:01:59]: CPU load is: 1.41
[09:01:59]: Attaching /root/devops/docker-tests/testing-samples/ui/espresso/AccessibilitySample to the docker container
[09:01:59]: $ docker run -v $PWD:/root/tests --privileged -t -d -p 6080:6080 -e DEVICE='samsung_galaxy_s8' --name espresso_container budtmo/docker-android-x86-8.1
[09:01:59]: ▸ 9ea06f0b13b813922d9ddb54ee5f5b3f9700365bd254ece757fd6fd0a31795b4
[09:02:00]: Waiting for Container to be in the Healthy state.
[09:02:02]: Container status: starting
[09:02:09]: Container status: starting
[09:02:16]: Container status: starting
[09:02:23]: Container status: starting
[09:02:30]: Container status: starting
[09:02:37]: Container status: starting


Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
[Capture]

**Comment by shasaaf** [comment]
Alright I try, earlier it was 120 secs with device nexus 5

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
Publicis Sapient
________________________________

**Comment by shasaaf** [comment]
Hi,

Increased the timeout to 200 secs, still the same


Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
[Capture]

**Comment by JoeSSS** [comment]
Please show the console log after you increased the timeout, It feels like it has something to do with this code: https://github.com/xing/mango/blob/c94fc1362093367cb4acd46bbd75ecacaff0c4d8/lib/fastlane/plugin/mango/helper/mango_helper.rb#L219-L225

But it is weird, since I think I covered all the possible output..

**Comment by shasaaf** [comment]
This is the output from the console

[06:54:07]: Link to VNC: http://10.128.0.14:6080
[06:54:07]: $ docker pull budtmo/docker-android-x86-8.1
[06:54:07]: ▸ Using default tag: latest
[06:54:07]: ▸ latest: Pulling from budtmo/docker-android-x86-8.1
[06:54:07]: ▸ Digest: sha256:e3c7a7e30b6cd02e1b6ce26101c62e6281e7725b9b59cc31ef2acbdc06c1dde8
[06:54:07]: ▸ Status: Image is up to date for budtmo/docker-android-x86-8.1:latest
[06:54:07]: $ docker network disconnect -f bridge espresso_container
[06:54:08]: ▸ Error response from daemon: endpoint espresso_container not found
[06:54:08]: Creating container: espresso_container
[06:54:08]: CPU load is: 1.59
[06:54:08]: Attaching /root/devops/docker-tests/testing-samples/ui/espresso/AccessibilitySample to the docker container
[06:54:08]: $ docker run -v $PWD:/root/tests --privileged -t -d -p 6080:6080 -e DEVICE='samsung_galaxy_s8' --name espresso_container budtmo/docker-android-x86-8.1
[06:54:08]: ▸ 9506f42d402cf8b5c67a2df30c1091ef894a2f5bd1260103e63b45210a27d672
[06:54:08]: $ docker exec -i espresso_container bash -l -c "kvm-ok > kvm-ok.txt"
[06:54:09]: ▸ mesg: ttyname failed: Inappropriate ioctl for device
[06:54:09]: ▸ bash: kvm-ok: command not found
[06:54:09]: $ docker exec -i espresso_container bash -l -c "cat kvm-ok.txt"
[06:54:09]: ▸ mesg: ttyname failed: Inappropriate ioctl for device
[06:54:09]: Waiting for Container to be in the Healthy state.
[06:54:11]: Container status: starting
[06:54:18]: Container status: starting
[06:54:25]: Container status: starting
[06:54:32]: Container status: starting
[06:54:39]: Container status: starting
[06:54:46]: Container status: starting
[06:54:53]: Container status: unhealthy
[06:55:00]: Container status: unhealthy
[06:55:07]: Container status: unhealthy
[06:55:14]: Container status: unhealthy
[06:55:21]: Container status: unhealthy


Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
[Capture]

**Comment by JoeSSS** [comment]
this isn't the whole log, I wonder - how long it stays unhealthy and which error message it says

**Comment by shasaaf** [comment]
This is the output

[04:16:41]: Container status: unhealthy
[04:16:48]: Container status: unhealthy
[04:16:53]: The Container failed to load after '200' seconds timeout. Reason: 'running'
[04:16:53]: Container is unhealthy. Exiting..
[04:16:53]: $ docker exec -i espresso_container bash -l -c "kvm-ok > kvm-ok.txt"
[04:16:53]: ▸ mesg: ttyname failed: Inappropriate ioctl for device
[04:16:53]: ▸ bash: kvm-ok: command not found
[04:16:53]: $ docker exec -i espresso_container bash -l -c "cat kvm-ok.txt"
[04:16:53]: ▸ mesg: ttyname failed: Inappropriate ioctl for device
[04:16:54]: Cleaning up emulator-5554 container
+------------------+------------------+
|            Lane Context             |
+------------------+------------------+
| DEFAULT_PLATFORM | android          |
| PLATFORM_NAME    | android          |
| LANE_NAME        | android espresso |
+------------------+------------------+

+------+---------------------+-------------+
|             fastlane summary             |
+------+---------------------+-------------+
| Step | Action              | Time (in s) |
+------+---------------------+-------------+
| 1    | default_platform    | 0           |
| 2    | run_dockerized_task | 595         |
+------+---------------------+-------------+

[04:17:04]: fastlane finished with errors

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
[Capture]

**Comment by JoeSSS** [comment]
Can you please try again after updating the gem? I just published a new version, as I realized that the one that was published was quite old

**Comment by shasaaf** [comment]
Hi Team,

Is it possible to run appium tests made on cucumber with Mango plugin, if yes, please let me know any image name.

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
[Capture]

**Comment by JoeSSS** [comment]
did it work with the new version?

With Appium - I don't know if the thing need something on top. What these tools provide is the working emulator, so you can run whatever you want inside the container. The image I posted before from Butomo has something for appium tho, maybe you want to use that one

**Comment by shasaaf** [comment]
No it still shows container unhealthy

Tried manually also with docker run, same thing

Thanks & Regards
Abhishek Sharma
Technical Lead DevOps | +91-9654586801 | Gurgaon
Publicis Sapient
________________________________

**Comment by JoeSSS** [comment]
there are no updates on this issue for a long time. Feel free to re-open if you still need help
